export const COMMAND_TYPES = [
  "task.create",
  "task.update",
  "task.file.write",
  "task.attachment.write",
  "task.move",
  "task.run",
  "task.interrupt",
  "task.comment",
  "task.decompose",
  "task.merge",
  "agent.step",
  "agent.wait_for_persona",
  "agent.wait_for_human",
  "agent.message",
  "agent.delegate_task",
  "chat.compact",
  "chat.reset_board",
  "agent.review_task",
  "agent.deploy_task",
  "workflow.create_task_spec",
  "workflow.update_task_spec",
  "workflow.approve_task_spec",
  "workflow.record_handoff",
  "workflow.record_decision",
  "workflow.record_validation",
  "workflow.record_technical_plan",
  "workflow.record_implementation_tasks",
  "workflow.record_review_report",
  "workflow.record_deployment_report",
  "workflow.record_summary",
  "workflow.run_definition_of_ready_gate",
  "workflow.run_definition_of_done_gate",
  "task.answer_input",
  "agent.complete_task",
  "agent.report_blocker",
  "agent.request_user_input",
  "agent.emit_artifact",
  "agent.chat",
  "settings.update"
];

export const QUERY_TYPES = [
  "board.snapshot",
  "task.detail",
  "task.files",
  "orchestrator.status",
  "settings.scope",
  "chat.history",
  "task.comments",
  "agent.logs",
  "chat.build",
  "provider.discover",
  "provider.models",
  "why_not_running"
];

export const EVENT_TYPES = [
  "task.created",
  "task.updated",
  "task.file.updated",
  "task.attachment.created",
  "planning.created",
  "planning.updated",
  "task.move_requested",
  "task.moved",
  "task.comment",
  "task.blocked",
  "task.problem",
  "task.run.blocked",
  "task.unblocked",
  "task.recovered",
  "agent.queued",
  "agent.started",
  "agent.event",
  "agent.transcript",
  "agent.message",
  "agent.waiting_for_persona",
  "agent.waiting_for_human",
  "chat.message",
  "agent.checkpoint_requested",
  "agent.interrupted",
  "agent.completed",
  "agent.failed",
  "agent.input_requested",
  "role.handoff",
  "human.input_requested",
  "human.input_received",
  "gate.passed",
  "gate.failed",
  "workflow.spec.created",
  "workflow.spec.updated",
  "workflow.spec.approved",
  "workflow.decision_recorded",
  "workflow.handoff_recorded",
  "workflow.validation_recorded",
  "workflow.technical_plan_recorded",
  "workflow.implementation_tasks_recorded",
  "workflow.review_report_recorded",
  "workflow.deployment_report_recorded",
  "workflow.summary_recorded",
  "workflow.done_requested",
  "workflow.direct_done_blocked",
  "workflow.dor_checked",
  "workflow.dod_checked",
  "deployment.recorded",
  "chat.created",
  "chat.compaction_requested",
  "chat.compacted",
  "delegation.requested",
  "delegation.result",
  "provider.missing_env",
  "artifact.emitted",
  "hook.started",
  "hook.completed",
  "hook.failed",
  "worktree.created",
  "worktree.updated",
  "worktree.removed",
  "subtasks.spawned",
  "orchestrator.reconciled",
  "subtask.merged",
  "merge.requested",
  "merge.completed",
  "merge.conflict",
  "merge.blocked",
  "settings.updated"
];

export const ROLE_IDS = ["manager", "product", "design", "architecture", "generalist", "engineering", "quality", "review", "deployment"];

export function commandEnvelope(type, payload = {}) {
  return { type, commandId: payload.commandId || `cmd-${Date.now()}`, ...payload };
}

export function queryEnvelope(type, payload = {}) {
  return { type, ...payload };
}
